### ISSUE TITLE
Getting dict rather than int for id

### ISSUE THREAD

**Issue by gpmidi** [fragforce/fragforce.org#210]
```
ffdonations.tasks.donations.update_donations_if_needed_participant[50acdd7b-c9ed-43d1-9305-7d26876df846] raised unexpected: TypeError("int() argument must be a string, a bytes-like object or a number, not 'dict'",)
2019-11-14T12:57:53.407921+00:00 app[beat.1]: Traceback (most recent call last):
2019-11-14T12:57:53.407924+00:00 app[beat.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/celery/app/trace.py", line 385, in trace_task
2019-11-14T12:57:53.407926+00:00 app[beat.1]:     R = retval = fun(*args, **kwargs)
2019-11-14T12:57:53.407929+00:00 app[beat.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/celery/app/trace.py", line 648, in __protected_call__
2019-11-14T12:57:53.407931+00:00 app[beat.1]:     return self.run(*args, **kwargs)
2019-11-14T12:57:53.407932+00:00 app[beat.1]:   File "/app/ffdonations/tasks/donations.py", line 163, in update_donations_if_needed_participant
2019-11-14T12:57:53.407935+00:00 app[beat.1]:     participant = ParticipantModel.objects.get(id=participantID)
2019-11-14T12:57:53.407937+00:00 app[beat.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
2019-11-14T12:57:53.407940+00:00 app[beat.1]:     return getattr(self.get_queryset(), name)(*args, **kwargs)
2019-11-14T12:57:53.407942+00:00 app[beat.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/django/db/models/query.py", line 399, in get
2019-11-14T12:57:53.407944+00:00 app[beat.1]:     clone = self.filter(*args, **kwargs)
2019-11-14T12:57:53.407946+00:00 app[beat.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/django/db/models/query.py", line 892, in filter
2019-11-14T12:57:53.407948+00:00 app[beat.1]:     return self._filter_or_exclude(False, *args, **kwargs)
2019-11-14T12:57:53.407949+00:00 app[beat.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/django/db/models/query.py", line 910, in _filter_or_exclude
2019-11-14T12:57:53.407952+00:00 app[beat.1]:     clone.query.add_q(Q(*args, **kwargs))
2019-11-14T12:57:53.407954+00:00 app[beat.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/django/db/models/sql/query.py", line 1290, in add_q
2019-11-14T12:57:53.407956+00:00 app[beat.1]:     clause, _ = self._add_q(q_object, self.used_aliases)
2019-11-14T12:57:53.407957+00:00 app[beat.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/django/db/models/sql/query.py", line 1318, in _add_q
2019-11-14T12:57:53.407959+00:00 app[beat.1]:     split_subq=split_subq, simple_col=simple_col,
2019-11-14T12:57:53.407961+00:00 app[beat.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/django/db/models/sql/query.py", line 1251, in build_filter
2019-11-14T12:57:53.407963+00:00 app[beat.1]:     condition = self.build_lookup(lookups, col, value)
2019-11-14T12:57:53.407965+00:00 app[beat.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/django/db/models/sql/query.py", line 1116, in build_lookup
2019-11-14T12:57:53.407967+00:00 app[beat.1]:     lookup = lookup_class(lhs, rhs)
2019-11-14T12:57:53.407969+00:00 app[beat.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/django/db/models/lookups.py", line 20, in __init__
2019-11-14T12:57:53.407971+00:00 app[beat.1]:     self.rhs = self.get_prep_lookup()
2019-11-14T12:57:53.407973+00:00 app[beat.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/django/db/models/lookups.py", line 70, in get_prep_lookup
2019-11-14T12:57:53.407975+00:00 app[beat.1]:     return self.lhs.output_field.get_prep_value(self.rhs)
2019-11-14T12:57:53.407978+00:00 app[beat.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/django/db/models/fields/__init__.py", line 1819, in get_prep_value
2019-11-14T12:57:53.407980+00:00 app[beat.1]:     return int(value)
2019-11-14T12:57:53.408040+00:00 app[beat.1]: TypeError: int() argument must be a string, a bytes-like object or a number, not 'dict'
````

**Comment by gpmidi** [comment]
Added logging in 12edeef65435eb21ec219745b1263d4e10ab636b
